### ISSUE TITLE
iib just stoped working today on Forge

### ISSUE THREAD

**Issue by ali0une** [zanllp/sd-webui-infinite-image-browsing#716]
Hi there.

iib just stoped working today on [Forge](https://github.com/lllyasviel/stable-diffusion-webui-forge).

Here is the error :

```
*** Error loading script: iib_setup.py
    Traceback (most recent call last):
      File "/whatever/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/whatever/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/whatever/stable-diffusion-webui-forge/extensions/sd-webui-infinite-image-browsing/scripts/iib_setup.py", line 1, in <module>
        from scripts.iib.api import infinite_image_browsing_api, send_img_path
    ModuleNotFoundError: No module named 'scripts.iib'
```

**Comment by Nyksia** [comment]
Since I have the same issue, feel like I should weigh in. There was another extension that had similar problem, the tag autocompletion. That one got fixed by just putting empty `__init__.py` in the folder that was refusing to load.
For this extension though, that doesn't seem to help, and it still refuses to load the `iib` folder here.

**Comment by Nyksia** [comment]
Turns out it is fixed by uninstalling the `gguf` package, if it was installed in Forge, as mentioned in lllyasviel/stable-diffusion-webui-forge#1134.

**Comment by Nyksia** [comment]
That said, after removing `gguf`, this extension stubbornly refuses to load it still. Which is weird in general.

**Comment by zanllp** [comment]
You can temporarily use the standalone version and the desktop version instead. I will look into how to address this issue later.

**Comment by ali0une** [comment]
As it's a [Forge related issue](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1134#issuecomment-2290925628) that is now fixed i think we can clode this one.

**Comment by Nyksia** [comment]
Been waiting to see if this'd get fixed on Forge's side of things, but while everything else got fixed, this extension still seems to have this issue. And I don't want to open up another issue, so felt like commenting about it here. @zanllp

**Comment by ali0une** [comment]
I had to git pull Forge and delete venv to get everything work again.

**Comment by Nyksia** [comment]
Nah, it is in fact still broken. I double checked and reinstalling the whole venv did not help. So the missing library error is still there for this extension.

**Comment by ali0une** [comment]
is the gguf python package still in your [requirements_versions.txt](https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/main/requirements_versions.txt) file in Forge root folder?

**Comment by zanllp** [comment]
> Nah, it is in fact still broken. I double checked and reinstalling the whole venv did not help. So the missing library error is still there for this extension.

I have no issues using it in the latest version of the Forge environment. Try updating it.

**Comment by Nyksia** [comment]
> I have no issues using IIB in the latest version of the Forge environment. Try updating it.

That's the thing, I did, Forge is latest and I deleted venv to get it to reinstall, for some reason it keeps throwing me that error.

**Comment by zanllp** [comment]
> > I have no issues using IIB in the latest version of the Forge environment. Try updating it.
> 
> That's the thing, I did, Forge is latest and I deleted venv to get it to reinstall, for some reason it keeps throwing me that error.


You can first make sure there is no `guff` under your [`venv`]
`ls -R venv | grep 'guff'`
